[package]
name = "writ"
description = "Command-line interface for writ"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
serde_json.workspace = true
tokio.workspace = true
writ-core = { path = "../writ-core" }

[lints]
workspace = true
